language: java
jdk: oraclejdk8
sudo: false
 
cache:
  directories:
    - ~/.m2

branches: 
 only:
 - master

env:
  global:
    secure: "dZRc32lyhribr0jRqqZzbhFVaaLZ0X+JfHWPb6ZSe5jRk0v9lTWXqjop/PKtcjE7/MB/VkCW4HC5JRWoy+Om2n3R0+84u7/+iGKz5lNh6Vm/NmUnyGrqnetsiHzzgFdSPz48vcpPcxItXLGbkXKw5Mac4qJ4QxFdku5cxY5WRfTHkDQysqyGPRoB7HxwD8Cp/Qcf05vBzUSNkad7vUVRdcNXujnGWex6TkdMGqqMjsSvuLUcIGLtpaG9M2lSISUseQ/F+oAyRBiPJdnUDLH4V0twz0n6LsN+5Bk5f8SDKAb/PEiuJzAJI6k8pMnCvlUA6hsMIyKgRzqa+sH1J60x80URnit6ax5z4U1Ufv5hioGGkPotvLW9Cn+qdGSB7RnUXPmbrWq5QG9J8t7vWq7+7JgVjSi42Ywv8kNj7ohc/z8KvDQo9QYwYeIoScDffM9cQy2z1RCU3wdJ19xFLuNdodU4rTdidqsI4UqsJ+IhifUA34VM/lbdhpdYwXYYWDruLIV4displTb7U6FuR9kz7L7e3nX45jznMToH9zcGDp67bM4DuyjS8N30R7C7ThqsAjK7w7CoJB/NpBoZNtIE3LBwFowrH2Pl0MHVoGNDzgLFx9OjSRdjBHQ9Mfhi/RXzd/Q7yZ12nHXSvYJdnORJlzxX0t3Zzw83ir6z1GlChyY="

addons:
  apt:
    packages:
      - graphviz

before_install:
# - chmod +x filter-maven-travis.sh
# - chmod +x push-to-gh-pages.sh
# - chmod +x codecov.sh
 - cd pom
 - (curl -s https://raw.githubusercontent.com/cstockloew/platform/master/uAAL.pom/src/scripts/settings.xml) > settings.xml
 - cp settings.xml $HOME/.m2/settings.xml
 - cat $HOME/.m2/settings.xml
 - (curl -s https://raw.githubusercontent.com/cstockloew/platform/master/uAAL.pom/src/scripts/ci.sh) > ci.sh
 - chmod +x ci.sh
 - export MY_REPO="cstockloew/middleware"
 - rm -rf ~/.m2/repository/org/universAAL/uAAL.pom

install:
 -

before_script:
 - cat /etc/mavenrc
 - echo "MAVEN_OPTS='-Xmx2g'" > ~/.mavenrc

script:
 - ci script
## - free -m
## - mvn clean install -DskipTests -Dorg.ops4j.pax.logging.DefaultServiceLog.level=WARN > /dev/null
# - ((((MAVEN_OPTS="-Xmx256m" mvn clean install -DskipTests -Dorg.ops4j.pax.logging.DefaultServiceLog.level=WARN > /dev/null; echo $? >&3) | ../filter-maven-travis.sh maven >&4) 3>&1) | (read xs; exit $xs)) 4>&1
#---------------
# - ((((MAVEN_OPTS="-Xmx256m" mvn clean install -DskipTests -Dorg.ops4j.pax.logging.DefaultServiceLog.level=WARN > /dev/null; echo $? >&3) | grep -i "INFO] Build" >&4) 3>&1) | (read xs; exit $xs)) 4>&1
# - mvn clean install -Dmaven.javadoc.skip=true -B
# - mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B
# - mkdir target || true
# - mkdir target/site || true
# - mkdir target/site/apidocs || true
# - mvn javadoc:aggregate -fn > target/site/apidocs/javadoc-aggregate.txt
# - mvn cobertura:cobertura -Dcobertura.aggregate=true  -Dcobertura.report.format=xml -fn > target/site/apidocs/cobertura.txt
# - export MAVEN_OPTS="-Xmx2048m"
# - mvn site -fn
# - mvn site -fae
# - MAVEN_OPTS="-Xmx1024m" JAVA_OPTS="-Xmx1024m" mvn site
# | grep -i "[INFO] Build"
# - mvn site:stage -DstagingDirectory=$HOME/site/uAAL.pom -fn > /dev/null
#####################
# - ((((mvn javadoc:javadoc -fae; echo $? >&3) | grep -i "INFO] Build" >&4) 3>&1) | (read xs; exit $xs)) 4>&1
# - ((((mvn javadoc:aggregate -fae; echo $? >&3) | grep -i "INFO] Build" >&4) 3>&1) | (read xs; exit $xs)) 4>&1
# - ((((mvn cobertura:cobertura -Dcobertura.aggregate=true -Dcobertura.report.format=xml -fae; echo $? >&3) | grep -i "INFO] Build" >&4) 3>&1) | (read xs; exit $xs)) 4>&1
# - ((((mvn surefire-report:report -Dsurefire-report.aggregate=true -fae; echo $? >&3) | grep -i "INFO] Build" >&4) 3>&1) | (read xs; exit $xs)) 4>&1
# - ((((MAVEN_OPTS="-Xmx512m" mvn javadoc:javadoc -fae; echo $? >&3) | grep -i "INFO] Build" >&4) 3>&1) | (read xs; exit $xs)) 4>&1
# - ((((mvn javadoc:javadoc -fae; echo $? >&3) | grep -i "INFO] Build" >&4) 3>&1) | (read xs; exit $xs)) 4>&1
## - ((((mvn javadoc:aggregate -fae; echo $? >&3) | grep -i "INFO] Build" >&4) 3>&1) | (read xs; exit $xs)) 4>&1
## - ((((mvn cobertura:cobertura -Dcobertura.aggregate=true -Dcobertura.report.format=xml -fae; echo $? >&3) | grep -i "INFO] Build" >&4) 3>&1) | (read xs; exit $xs)) 4>&1
## - ((((mvn cobertura:cobertura -Dcobertura.aggregate=true -Dcobertura.report.format=html -DskipTests -fae; echo $? >&3) | grep -i "INFO] Build" >&4) 3>&1) | (read xs; exit $xs)) 4>&1
# - ((((MAVEN_OPTS="-Xmx512m" mvn surefire-report:report -Dsurefire-report.aggregate=true -fae; echo $? >&3) | grep -i "INFO] Build" >&4) 3>&1) | (read xs; exit $xs)) 4>&1
# - MAVEN_OPTS="-Xmx512m" mvn surefire-report:report -Dsurefire-report.aggregate=true -fae
# - export JAVA_TOOL_OPTIONS="-Xmx3g"
# - JAVA_TOOL_OPTIONS="-Xmx3g" MAVEN_OPTS="-Xmx3g" JAVA_OPTS="--Xmx4" mvn site:site -Dsurefire.argLine="--Xmx3g" -Dcobertura.maxmem=3g -DskipTests -Dcobertura.skip  -Dmaven.javadoc.skip=true -Dmaxmemory=3g -Djavadoc.maxmemory=3g -fn -e
## - mvn site:site -DskipTests -Dcobertura.skip -Dmaven.javadoc.skip=true -Duaal.report=ci-repo -fn -e
# - ulimit -a
# - free -m
# - echo Delete all coverage reports except the aggregated one!
# - mv target/site/cobertura/coverage.xml target/site/cobertura/coverage2.xml
# - find .. -name "coverage.xml" -type f -delete
# - mv target/site/cobertura/coverage2.xml target/site/cobertura/coverage.xml

after_success:
 - ci success
# - mvn deploy -DskipTests -DaltDeploymentRepository=uaal-nightly::default::http://depot.universaal.org/maven-repo/nightly/
# - ../push-to-gh-pages.sh
# - export GH_TOKEN="deleted"
# - export NIGHTLY_PASSWORD="deleted"
# - export NIGHTLY_USERNAME="deleted"
# - echo "$GH_TOKEN"
# - mvn org.eluder.coveralls:coveralls-maven-plugin:4.3.0:report -e
# - bash <(curl -s https://codecov.io/bash)
# - ../codecov.sh

notifications:
  email: false
